# Generated by Django 5.1.4 on 2024-12-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataentry", "0003_alter_student_roll_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=20)),
            ],
        ),
    ]
