# Generated by Django 5.1.4 on 2025-02-09 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockannalysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_price",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "price_changed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "percentage_change",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "previous_close",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "week_52_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "week_52_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("market_cap", models.CharField(blank=True, max_length=255, null=True)),
                ("pe_ratio", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dividend_yield",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stockannalysis.stock",
                    ),
                ),
            ],
        ),
    ]
